# OpenTelemetry Collector Configuration for Automagik Telemetry
# Receives OTLP data and exports to ClickHouse

receivers:
  # OTLP receiver for HTTP (JSON)
  otlp:
    protocols:
      http:
        endpoint: 0.0.0.0:4318
        cors:
          allowed_origins:
            - "*"
          allowed_headers:
            - "*"
      grpc:
        endpoint: 0.0.0.0:4317

  # Prometheus receiver for collector self-monitoring
  prometheus:
    config:
      scrape_configs:
        - job_name: 'otel-collector'
          scrape_interval: 10s
          static_configs:
            - targets: ['localhost:8888']

processors:
  # Batch processor for efficiency (matches production: 10s or 1024 items)
  batch:
    timeout: 10s
    send_batch_size: 1024
    send_batch_max_size: 1024

  # Memory limiter to prevent OOM
  memory_limiter:
    check_interval: 1s
    limit_mib: 512
    spike_limit_mib: 128

  # Resource processor to add/modify attributes (matches production)
  resource:
    attributes:
      - key: service.namespace
        value: namastex
        action: insert
      - key: deployment.environment
        value: local-dev
        action: insert
      - key: collector.name
        value: automagik-collector-local
        action: insert

exporters:
  # Debug exporter for debugging (replaces deprecated logging exporter)
  debug:
    verbosity: normal
    sampling_initial: 5
    sampling_thereafter: 200

  # Prometheus exporter for metrics
  prometheus:
    endpoint: "0.0.0.0:8889"
    namespace: automagik_telemetry

  # Note: ClickHouse export is handled directly by SDKs for better performance
  # SDKs write directly to ClickHouse using custom schema and batching

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [memory_limiter, resource, batch]
      exporters: [debug]

    metrics:
      receivers: [prometheus, otlp]
      processors: [batch]
      exporters: [prometheus, debug]

    logs:
      receivers: [otlp]
      processors: [batch]
      exporters: [debug]

  telemetry:
    logs:
      level: info

  extensions: [health_check]

extensions:
  health_check:
    endpoint: 0.0.0.0:13133
