# OpenTelemetry Collector Configuration for Automagik Telemetry
# Receives OTLP data and exports to ClickHouse

receivers:
  # OTLP receiver for HTTP (JSON)
  otlp:
    protocols:
      http:
        endpoint: 0.0.0.0:4318
        cors:
          allowed_origins:
            - "*"
          allowed_headers:
            - "*"
      grpc:
        endpoint: 0.0.0.0:4317

  # Prometheus receiver for collector self-monitoring
  prometheus:
    config:
      scrape_configs:
        - job_name: 'otel-collector'
          scrape_interval: 10s
          static_configs:
            - targets: ['localhost:8888']

processors:
  # Batch processor for efficiency (matches production: 10s or 1024 items)
  batch:
    timeout: 10s
    send_batch_size: 1024
    send_batch_max_size: 1024

  # Memory limiter to prevent OOM
  memory_limiter:
    check_interval: 1s
    limit_mib: 512
    spike_limit_mib: 128

  # Resource processor to add/modify attributes (matches production)
  resource:
    attributes:
      - key: service.namespace
        value: namastex
        action: insert
      - key: deployment.environment
        value: local-dev
        action: insert
      - key: collector.name
        value: automagik-collector-local
        action: insert

exporters:
  # ClickHouse exporter via HTTP
  clickhouse:
    endpoint: ${env:CLICKHOUSE_ENDPOINT}
    database: ${env:CLICKHOUSE_DATABASE}
    username: ${env:CLICKHOUSE_USER}
    password: ${env:CLICKHOUSE_PASSWORD}
    ttl: 72h
    traces_table_name: traces
    timeout: 10s
    retry_on_failure:
      enabled: true
      initial_interval: 5s
      max_interval: 30s
      max_elapsed_time: 300s

  # Debug exporter for debugging (replaces deprecated logging exporter)
  debug:
    verbosity: normal
    sampling_initial: 5
    sampling_thereafter: 200

  # Prometheus exporter for metrics
  prometheus:
    endpoint: "0.0.0.0:8889"
    namespace: automagik_telemetry

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [memory_limiter, resource, batch]
      exporters: [debug]

    metrics:
      receivers: [prometheus]
      processors: [batch]
      exporters: [debug]

  telemetry:
    logs:
      level: info
