name: Python SDK CI

on:
  push:
    branches: [main]
    paths:
      - 'python/**'
      - '.github/workflows/python-ci.yml'
  pull_request:
    branches: [main]
    paths:
      - 'python/**'
      - '.github/workflows/python-ci.yml'

jobs:
  test:
    name: Test Python ${{ matrix.python-version }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ['3.12', '3.13']

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'pip'

      - name: Install dependencies
        run: |
          cd python
          python -m pip install --upgrade pip
          pip install -e ".[dev]"

      - name: Run ruff linter
        run: |
          cd python
          ruff check src tests

      - name: Run mypy type checking
        run: |
          cd python
          mypy src

      - name: Run pytest with coverage
        run: |
          cd python
          pytest --cov=automagik_telemetry --cov-report=xml --cov-report=term-missing

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        if: matrix.python-version == '3.12'
        with:
          files: ./python/coverage.xml
          flags: python
          name: python-${{ matrix.python-version }}
          token: ${{ secrets.CODECOV_TOKEN }}
          fail_ci_if_error: false

  lint-format:
    name: Lint and Format Check
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: 'pip'

      - name: Install ruff
        run: pip install ruff

      - name: Check ruff formatting
        run: |
          cd python
          ruff format --check src tests

      - name: Run ruff linter
        run: |
          cd python
          ruff check src tests
