name: TypeScript SDK CI

on:
  push:
    branches: [main]
    paths:
      - 'typescript/**'
      - '.github/workflows/typescript-ci.yml'
  pull_request:
    branches: [main]
    paths:
      - 'typescript/**'
      - '.github/workflows/typescript-ci.yml'

jobs:
  test:
    name: Test Node.js ${{ matrix.node-version }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        node-version: ['18', '20', '22']

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 8

      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'
          cache-dependency-path: 'typescript/pnpm-lock.yaml'

      - name: Install dependencies
        run: |
          cd typescript
          pnpm install --frozen-lockfile

      - name: Run eslint
        run: |
          cd typescript
          pnpm run lint

      - name: Check prettier formatting
        run: |
          cd typescript
          pnpm exec prettier --check src

      - name: Run TypeScript build
        run: |
          cd typescript
          pnpm run build

      - name: Run jest tests with coverage
        run: |
          cd typescript
          pnpm run test -- --coverage --coverageReporters=xml --coverageReporters=text

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        if: matrix.node-version == '20'
        with:
          files: ./typescript/coverage/coverage-final.json
          flags: typescript
          name: typescript-node-${{ matrix.node-version }}
          token: ${{ secrets.CODECOV_TOKEN }}
          fail_ci_if_error: false

  lint-format:
    name: Lint and Format Check
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 8

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'pnpm'
          cache-dependency-path: 'typescript/pnpm-lock.yaml'

      - name: Install dependencies
        run: |
          cd typescript
          pnpm install --frozen-lockfile

      - name: Run eslint
        run: |
          cd typescript
          pnpm run lint

      - name: Check prettier formatting
        run: |
          cd typescript
          pnpm exec prettier --check src

      - name: Check TypeScript types
        run: |
          cd typescript
          pnpm exec tsc --noEmit
